### ISSUE TITLE
Add option to replace space with undercore

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__extended_tag_edit_add_dialog#1]
Present behavior to move to a new line. Enter should be sufficient for that.
Rationale: Underscoring is a painful process.

**Comment by ijgnd** [comment]
try this: https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/releases/download/0.2/anki__extended_tag_edit_add_dialog__2020-02-10.ankiaddon

adjust the config: and adjust the config key `"tag dialog space": ""` to `"tag dialog space": "_"`

let me know if it works. could you also test with the latest versions of night mode.

**Comment by ghost** [comment]
Works perfectly with both, if you mean the native dark mode.
Thank you.
