### ISSUE TITLE
errors when set "basic_but_quick" to false

### ISSUE THREAD

**Issue by Laern2Do** [ijgnd/anki__extended_tag_edit_add_dialog#6]
Hi there, i stumble across another one,

this is for when I set "basic_but_quick" to false to use the auto-completer. the errors below is thrown when i use "ctrl + j" (edit tag for current line) after the tag dialog is open, "ctrl + t, d"

![image](https://user-images.githubusercontent.com/63658303/94768642-97563b80-0375-11eb-8a49-2eb9d479c997.png)

Thanks!

anki ver 2.1.26 window 10

**Comment by ijgnd** [comment]
Thanks for this report. 

I'm quite busy at the moment so I only did a quick fix without much testing. The error should no longer occur but I haven't checked the functionality if you have enabled  "basic_but_quick" . So I need your help: Could you try my most recent version and let me know if you find any other problems? If it works for a few days without problems I can upload it to ankiweb. 

You can download the most recent version from github [here](https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/releases/download/%236_test/anki__extended_tag_edit_add_dialog__2020-10-08.ankiaddon). Just drag and drop this file into the add-on window, see this video: [installing ankiaddon files from outside of ankiweb](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif)

**Comment by Laern2Do** [comment]
nice :)! 

looking good so far on this errors. i was hoping for the slight chance that the shortcuts issue for "pdf searching..." and "persistent editor" was also address for this fix ^^. Either way, im very thankful that you took the time to take care of this knowing you re very busy.

I appreciate it

thx!

**Comment by ijgnd** [comment]
About the "persistent editor": I most likely won't fix it for your old Anki version 2.1.26 - I don't use this version anymore and soon very few people will use it. Once you've updated to the most recent anki version (or at least 2.1.31 or newer) the most recent version of "persistent editor" for these newer Anki versions will work with the current version of my add-on.

the shortcut for "pdf searching..." is still on the todo list but it's low priority.

**Comment by ijgnd** [comment]
just a note to myself: My commit e56e040c66dedcadc209577beac0066ad67eaeac was likely related to this problem ...
